name: CSV Lint workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v1
    - name: Run csv-lint
      uses: blackstar257/docker-csvlint@master
      env:
        ACTION_STATE_NAME: "breweries.csv"
